name: cv-env
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Downgrade to 3.10 for better compatibility
  - pytorch
  - torchvision
  - ftfy
  - regex
  - tqdm
  - pillow
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pip
  - opencv  # Just opencv from conda-forge
  - dlib    # Just dlib from conda-forge
  - pip:
      - git+https://github.com/openai/CLIP.git
  - mediapipe
  - sklearn
  - scikit-image